# Generated by Django 4.1.7 on 2023-03-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phoneNum', models.CharField(max_length=50)),
                ('gpa', models.FloatField(default=0)),
            ],
        ),
    ]
