# Generated by Django 4.1.7 on 2023-03-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0002_alter_student_email_alter_student_phonenum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='ID',
            new_name='id',
        ),
    ]
