# Generated by Django 4.1.7 on 2023-03-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0003_rename_id_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='surname',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
